name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Atualiza a cada hora
  workflow_dispatch: # Permite rodar manualmente
push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ETRICS_TOKEN }}
          user: AdamGabriel1
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
